version: "3.8"

services:
  traefik:
    deploy:
      placement:
        constraints:
          - node.role == manager

  frontend:
    deploy:
      replicas: 9
      placement:
        max_replicas_per_node: 1
        constraints:
          - node.role != manager
      update_config:
        parallelism: 3
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 5

  backend:
    deploy:
      replicas: 9
      placement:
        max_replicas_per_node: 1
        constraints:
          - node.role != manager
      update_config:
        parallelism: 3
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 5

  tf-serving:
    deploy:
      replicas: 9
      placement:
        max_replicas_per_node: 1
        constraints:
          - node.role != manager
      update_config:
        parallelism: 3
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 5
