version: "3.8"

services:
  traefik:
    image: traefik:v2.3
    ports:
      - 80:80
      - 8080:8080
    command:
      - "--accesslog"
      - "--log"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.swarmmode=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"

  frontend:
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.http.middlewares.app-strip-prefix.stripprefix.prefixes=/app"
        - "traefik.http.routers.frontend.middlewares=app-strip-prefix@docker"
        - "traefik.http.routers.frontend.rule=PathPrefix(`/app`, `/app/`)"
        - "traefik.http.routers.frontend.entrypoints=web"
        - "traefik.http.services.frontend.loadbalancer.server.port=80"

  backend:
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.backend.rule=PathPrefix(`/api/`)"
        - "traefik.http.routers.backend.entrypoints=web"
        - "traefik.http.services.backend.loadbalancer.server.port=80"
