from functools import reduce

MODEL_ARCHITECTURES = ['gpt2', 'lstm']
TARGETS = ['aki', 'sepsis', 'mi', 'vancomycin']
N_FEATURES = {
    'sepsis': 225,
    'mi': 221,
    'vancomycin': 224,
    'aki': 16,
}
N_TIMESTEPS = {
    'sepsis': 14,
    'mi': 14,
    'vancomycin': 14,
    'aki': 8,
}

GENDERS = set(['男', '女'])
ETHNICITIES = set([
    '汉族', '满族', '蒙古族', '回族', '藏族', '维吾尔族', '苗族', '彝族', '壮族', '布依族', '侗族',
    '瑶族', '白族', '土家族', '哈尼族', '哈萨克族', '傣族', '黎族', '傈僳族', '佤族', '畲族', '高山族',
    '拉祜族', '水族', '东乡族', '纳西族', '景颇族', '柯尔克孜族', '土族', '达斡尔族', '仫佬族', '羌族',
    '布朗族', '撒拉族', '毛南族', '仡佬族', '锡伯族', '阿昌族', '普米族', '朝鲜族', '塔吉克族', '怒族',
    '乌孜别克族', '俄罗斯族', '鄂温克族', '德昂族', '保安族', '裕固族', '京族', '塔塔尔族', '独龙族',
    '鄂伦春族', '赫哲族', '门巴族', '珞巴族', '基诺族',
])

FEATURE_MAP = {
    'RBCs': {833, 4197},
    'WBCs': {51300, 51301, 220546, 1542, 1127, 4200, 861},
    'platelets': {51265, 227457, 3789, 6256, 225170, 30006, 828},
    'hemoglobin': {51222, 220228, 814},
    'hemocrit': {3761, 220545, 226540, 813},
    'atypical lymphocytes': {794, 225637},
    'bands': {795, 225638},
    'basophils': {796, 225639},
    'eosinophils': {225640, 797},
    'neutrophils': {225643},
    'lymphocytes': {225641, 798},
    'monocytes': {225642, 799},
    'polymorphonuclear leukocytes': {800},
    'temperature': {223761, 678, 679},
    'heart rate': {3494, 220045, 220046, 220047, 211},
    'respiratory rate': {618, 619, 224688, 224689, 224690, 220210},
    'systolic': {6, 220050, 220179, 666, 220059, 225309, 226850, 226852, 224167, 227243, 6701, 51, 228152, 442, 455, 7643, 480, 482, 484, 492, 3313, 3315, 3317, 3319, 3321, 3323, 3325},
    'diastolic': {8448, 224643, 220051, 220180, 153, 220060, 225310, 226851, 226853, 227242, 8364, 8368, 8502, 228151, 8504, 8505, 8503, 8506, 8507, 8508, 8555, 8440, 8441, 8444, 8445, 8446},
    'pulse oximetry': {220277},
    'troponin': {851, 227429},
    'HDL': {220624},
    'LDL': {225671, 227441, 225670, 7431},
    'BUN': {51006, 1162, 781, 5876, 225624, 3737},
    'INR': {44481, 227467, 815, 220561, 1530, 42527},
    'PTT': {227466, 220562, 3796, 825, 1533},
    'PT': {824, 1286},
    'triglycerides': {850, 3811, 1540, 225693},
    'creatinine': {3750, 220615, 5811, 1525, 791},
    'glucose': {3744, 3745, 2338, 225664, 228388, 807, 3816, 226537, 811, 220621, 1455, 1812, 3447, 1529, 1310},
    'sodium': {50824, 50983, 1536, 5189, 837, 228389, 228390, 220645, 226534, 3803},
    'potassium': {50822, 50971, 42628, 225925, 227464, 3725, 225166, 46611, 1821, 4381, 44711, 2856, 5167, 46263, 45627, 222139, 829, 44479, 5195, 30029, 3792, 30297, 44762, 30299, 43872, 220640, 4194, 41956, 43238, 226535, 42728, 41450, 227442, 46453, 45430, 3578, 1535},
    'chloride': {228385, 228386, 3747, 226536, 1523, 788, 220602},
    'bicarbonate': {46592, 6146, 220995, 44166, 3528, 227533, 30030, 225165, 46362, 221211},
    'blood culture': {70016, 3333, 938, 70060, 942, 225401, 70011, 70012, 70013, 70014},
    'urine culture': {941, 225454, 4855},
    'surface culture': {6043},
    'sputum culture': {2929, 225451},
    'wound culture': {225816},
    'Inspired O2 Fraction': {223835},
    'central venous pressure': {220074},
    'PEEP Set': {506, 220339},
    'tidal volume': {683, 224684},
    'anion gap': {227073, 3732},
    'daily weight': {763, 224639},
    'tobacco': {225108, 227687},
    'diabetes': {227007},
    'history of CV events': {225811},
    'bicarbonate': {50882},
    'chloride': {50902},
    'creatinine': {50912},
    'glucose': {50931},
    'magnesium': {50960},
    'weight': {763, 224639},  # kg
    'height': {
        226707, 1394,  # inches
        226730,  # cm
    },
}
REV_FEATURE_MAP = {
    itemid: feature
    for feature, itemids in FEATURE_MAP.items()
    for itemid in itemids
}
ITEM_IDS = reduce(
    lambda x, y: x.union(y),
    FEATURE_MAP.values(),
)

# feature list of all the models (ordering is important)
AKI_FEATURES = [
    'bicarbonate', 'BUN', 'chloride', 'creatinine', 'glucose', 'height',
    'hemoglobin', 'magnesium', 'platelets', 'potassium', 'sodium', 'WBCs',
    'weight', 'age', 'gender', 'black',
]
SEPSIS_FEATURES = [
    'BUN', 'HDL', 'INR', 'Inspired O2 Fraction', 'LDL', 'PEEP Set', 'PTT', 'RBCs', 'WBCs',
    'anion gap', 'atypical lymphocytes', 'bands', 'basophils', 'blood culture',
    'central venous pressure', 'chloride', 'creatinine', 'daily weight', 'diabetes',
    'diastolic', 'eosinophils', 'glucose', 'heart rate', 'hemocrit', 'hemoglobin',
    'lymphocytes', 'monocytes', 'neutrophils', 'platelets', 'polymorphonuclear leukocytes',
    'potassium_x', 'pulse oximetry', 'respiratory rate', 'sodium', 'systolic', 'temperature',
    'tidal volume', 'tobacco', 'triglycerides', 'troponin', 'BUN_std', 'HDL_std', 'INR_std',
    'Inspired O2 Fraction_std', 'LDL_std', 'PEEP Set_std', 'PTT_std', 'RBCs_std', 'WBCs_std',
    'anion gap_std', 'atypical lymphocytes_std', 'bands_std', 'basophils_std',
    'central venous pressure_std', 'chloride_std', 'creatinine_std', 'diastolic_std',
    'eosinophils_std', 'glucose_std', 'heart rate_std', 'hemocrit_std', 'hemoglobin_std',
    'lymphocytes_std', 'monocytes_std', 'neutrophils_std', 'platelets_std',
    'polymorphonuclear leukocytes_std', 'potassium_std', 'pulse oximetry_std',
    'respiratory rate_std', 'sodium_std', 'systolic_std', 'temperature_std', 'tidal volume_std',
    'triglycerides_std', 'troponin_std', 'BUN_min', 'HDL_min', 'INR_min',
    'Inspired O2 Fraction_min', 'LDL_min', 'PEEP Set_min', 'PTT_min', 'RBCs_min', 'WBCs_min',
    'anion gap_min', 'atypical lymphocytes_min', 'bands_min', 'basophils_min',
    'central venous pressure_min', 'chloride_min', 'creatinine_min', 'diastolic_min',
    'eosinophils_min', 'glucose_min', 'heart rate_min', 'hemocrit_min', 'hemoglobin_min',
    'lymphocytes_min', 'monocytes_min', 'neutrophils_min', 'platelets_min',
    'polymorphonuclear leukocytes_min', 'potassium_min', 'pulse oximetry_min',
    'respiratory rate_min', 'sodium_min', 'systolic_min', 'temperature_min', 'tidal volume_min',
    'triglycerides_min', 'troponin_min', 'BUN_max', 'HDL_max', 'INR_max',
    'Inspired O2 Fraction_max', 'LDL_max', 'PEEP Set_max', 'PTT_max', 'RBCs_max', 'WBCs_max',
    'anion gap_max', 'atypical lymphocytes_max', 'bands_max', 'basophils_max',
    'central venous pressure_max', 'chloride_max', 'creatinine_max', 'diastolic_max',
    'eosinophils_max', 'glucose_max', 'heart rate_max', 'hemocrit_max', 'hemoglobin_max',
    'lymphocytes_max', 'monocytes_max', 'neutrophils_max', 'platelets_max',
    'polymorphonuclear leukocytes_max', 'potassium_max', 'pulse oximetry_max',
    'respiratory rate_max', 'sodium_max', 'systolic_max', 'temperature_max', 'tidal volume_max',
    'triglycerides_max', 'troponin_max', 'BLACK', 'age', 'M', '0.9% Sodium Chloride', 'SMX-TMP',
    'acetominophen', 'albuterol', 'amiodarone', 'amoxicillin', 'ampicillin-sulbactam', 'asprin',
    'atenolol', 'atropine', 'calcium gluconate', 'captopril', 'carvedilol', 'cefazolin',
    'cefepime', 'ceftriaxone', 'clonazepam', 'clopidogrel', 'dextrose', 'diazepam',
    'digoxin(?!.*fab)', 'diltiazem', 'diphenhydramine', 'enoxaparin', 'epoetin', 'fentanyl',
    'fentanyl citrate', 'fluconazole', 'fondaparinux', 'furosemide', 'glucagon', 'haloperidol',
    'heparin', 'hydralazine', 'hydrochlorothiazide', 'hydromorphone', 'insulin', 'ipratropium',
    'labetalol', 'levetiracetam', 'levofloxacin', 'levothyroxine', 'lisinopril',
    'magensium sulfate', 'meropenem', 'metoclopramide', 'metoprolol', 'metronidazole', 'midazolam',
    'nafcillin', 'neostigmine', 'nitroglycerin', 'nitroprusside', 'norepinephrine', 'ondansetron',
    'oxacillin', 'oxycodone', 'pantoprazole', 'penicillin', 'phenylephrine', 'phenytoin',
    'phytonadione', 'piperacillin', 'potassium_y', 'prednisone', 'propofol', 'ranitidine',
    'statin', 'tacrolimus', 'trazodone', 'vancomycin', 'vasopressin', 'warfarin', 'zolpidem',
]
MI_FEATURES = [
    'BUN', 'HDL', 'INR', 'Inspired O2 Fraction', 'LDL', 'PEEP Set', 'PTT', 'RBCs', 'WBCs',
    'anion gap', 'atypical lymphocytes', 'bands', 'basophils', 'blood culture',
    'central venous pressure', 'chloride', 'creatinine', 'daily weight', 'diabetes',
    'diastolic', 'eosinophils', 'glucose', 'heart rate', 'hemocrit', 'hemoglobin',
    'lymphocytes', 'monocytes', 'neutrophils', 'platelets', 'polymorphonuclear leukocytes',
    'potassium_x', 'pulse oximetry', 'respiratory rate', 'sodium', 'systolic', 'temperature',
    'tidal volume', 'tobacco', 'triglycerides', 'BUN_std', 'HDL_std', 'INR_std',
    'Inspired O2 Fraction_std', 'LDL_std', 'PEEP Set_std', 'PTT_std', 'RBCs_std', 'WBCs_std',
    'anion gap_std', 'atypical lymphocytes_std', 'bands_std', 'basophils_std',
    'central venous pressure_std', 'chloride_std', 'creatinine_std', 'diastolic_std',
    'eosinophils_std', 'glucose_std', 'heart rate_std', 'hemocrit_std', 'hemoglobin_std',
    'lymphocytes_std', 'monocytes_std', 'neutrophils_std', 'platelets_std',
    'polymorphonuclear leukocytes_std', 'potassium_std', 'pulse oximetry_std',
    'respiratory rate_std', 'sodium_std', 'systolic_std', 'temperature_std', 'tidal volume_std',
    'triglycerides_std', 'BUN_min', 'HDL_min', 'INR_min',
    'Inspired O2 Fraction_min', 'LDL_min', 'PEEP Set_min', 'PTT_min', 'RBCs_min', 'WBCs_min',
    'anion gap_min', 'atypical lymphocytes_min', 'bands_min', 'basophils_min',
    'central venous pressure_min', 'chloride_min', 'creatinine_min', 'diastolic_min',
    'eosinophils_min', 'glucose_min', 'heart rate_min', 'hemocrit_min', 'hemoglobin_min',
    'lymphocytes_min', 'monocytes_min', 'neutrophils_min', 'platelets_min',
    'polymorphonuclear leukocytes_min', 'potassium_min', 'pulse oximetry_min',
    'respiratory rate_min', 'sodium_min', 'systolic_min', 'temperature_min', 'tidal volume_min',
    'triglycerides_min', 'BUN_max', 'HDL_max', 'INR_max',
    'Inspired O2 Fraction_max', 'LDL_max', 'PEEP Set_max', 'PTT_max', 'RBCs_max', 'WBCs_max',
    'anion gap_max', 'atypical lymphocytes_max', 'bands_max', 'basophils_max',
    'central venous pressure_max', 'chloride_max', 'creatinine_max', 'diastolic_max',
    'eosinophils_max', 'glucose_max', 'heart rate_max', 'hemocrit_max', 'hemoglobin_max',
    'lymphocytes_max', 'monocytes_max', 'neutrophils_max', 'platelets_max',
    'polymorphonuclear leukocytes_max', 'potassium_max', 'pulse oximetry_max',
    'respiratory rate_max', 'sodium_max', 'systolic_max', 'temperature_max', 'tidal volume_max',
    'triglycerides_max', 'BLACK', 'age', 'M', '0.9% Sodium Chloride', 'SMX-TMP',
    'acetominophen', 'albuterol', 'amiodarone', 'amoxicillin', 'ampicillin-sulbactam', 'asprin',
    'atenolol', 'atropine', 'calcium gluconate', 'captopril', 'carvedilol', 'cefazolin',
    'cefepime', 'ceftriaxone', 'clonazepam', 'clopidogrel', 'dextrose', 'diazepam',
    'digoxin(?!.*fab)', 'diltiazem', 'diphenhydramine', 'enoxaparin', 'epoetin', 'fentanyl',
    'fentanyl citrate', 'fluconazole', 'fondaparinux', 'furosemide', 'glucagon', 'haloperidol',
    'heparin', 'hydralazine', 'hydrochlorothiazide', 'hydromorphone', 'insulin', 'ipratropium',
    'labetalol', 'levetiracetam', 'levofloxacin', 'levothyroxine', 'lisinopril',
    'magensium sulfate', 'meropenem', 'metoclopramide', 'metoprolol', 'metronidazole', 'midazolam',
    'nafcillin', 'neostigmine', 'nitroglycerin', 'nitroprusside', 'norepinephrine', 'ondansetron',
    'oxacillin', 'oxycodone', 'pantoprazole', 'penicillin', 'phenylephrine', 'phenytoin',
    'phytonadione', 'piperacillin', 'potassium_y', 'prednisone', 'propofol', 'ranitidine',
    'statin', 'tacrolimus', 'trazodone', 'vancomycin', 'vasopressin', 'warfarin', 'zolpidem',
]
VANCOMYCIN_FEATURES = [
    'BUN', 'HDL', 'INR', 'Inspired O2 Fraction', 'LDL', 'PEEP Set', 'PTT', 'RBCs', 'WBCs',
    'anion gap', 'atypical lymphocytes', 'bands', 'basophils', 'blood culture',
    'central venous pressure', 'chloride', 'creatinine', 'daily weight', 'diabetes',
    'diastolic', 'eosinophils', 'glucose', 'heart rate', 'hemocrit', 'hemoglobin',
    'lymphocytes', 'monocytes', 'neutrophils', 'platelets', 'polymorphonuclear leukocytes',
    'potassium_x', 'pulse oximetry', 'respiratory rate', 'sodium', 'systolic', 'temperature',
    'tidal volume', 'tobacco', 'triglycerides', 'troponin', 'BUN_std', 'HDL_std', 'INR_std',
    'Inspired O2 Fraction_std', 'LDL_std', 'PEEP Set_std', 'PTT_std', 'RBCs_std', 'WBCs_std',
    'anion gap_std', 'atypical lymphocytes_std', 'bands_std', 'basophils_std',
    'central venous pressure_std', 'chloride_std', 'creatinine_std', 'diastolic_std',
    'eosinophils_std', 'glucose_std', 'heart rate_std', 'hemocrit_std', 'hemoglobin_std',
    'lymphocytes_std', 'monocytes_std', 'neutrophils_std', 'platelets_std',
    'polymorphonuclear leukocytes_std', 'potassium_std', 'pulse oximetry_std',
    'respiratory rate_std', 'sodium_std', 'systolic_std', 'temperature_std', 'tidal volume_std',
    'triglycerides_std', 'troponin_std', 'BUN_min', 'HDL_min', 'INR_min',
    'Inspired O2 Fraction_min', 'LDL_min', 'PEEP Set_min', 'PTT_min', 'RBCs_min', 'WBCs_min',
    'anion gap_min', 'atypical lymphocytes_min', 'bands_min', 'basophils_min',
    'central venous pressure_min', 'chloride_min', 'creatinine_min', 'diastolic_min',
    'eosinophils_min', 'glucose_min', 'heart rate_min', 'hemocrit_min', 'hemoglobin_min',
    'lymphocytes_min', 'monocytes_min', 'neutrophils_min', 'platelets_min',
    'polymorphonuclear leukocytes_min', 'potassium_min', 'pulse oximetry_min',
    'respiratory rate_min', 'sodium_min', 'systolic_min', 'temperature_min', 'tidal volume_min',
    'triglycerides_min', 'troponin_min', 'BUN_max', 'HDL_max', 'INR_max',
    'Inspired O2 Fraction_max', 'LDL_max', 'PEEP Set_max', 'PTT_max', 'RBCs_max', 'WBCs_max',
    'anion gap_max', 'atypical lymphocytes_max', 'bands_max', 'basophils_max',
    'central venous pressure_max', 'chloride_max', 'creatinine_max', 'diastolic_max',
    'eosinophils_max', 'glucose_max', 'heart rate_max', 'hemocrit_max', 'hemoglobin_max',
    'lymphocytes_max', 'monocytes_max', 'neutrophils_max', 'platelets_max',
    'polymorphonuclear leukocytes_max', 'potassium_max', 'pulse oximetry_max',
    'respiratory rate_max', 'sodium_max', 'systolic_max', 'temperature_max', 'tidal volume_max',
    'triglycerides_max', 'troponin_max', 'BLACK', 'age', 'M', '0.9% Sodium Chloride', 'SMX-TMP',
    'acetominophen', 'albuterol', 'amiodarone', 'amoxicillin', 'ampicillin-sulbactam', 'asprin',
    'atenolol', 'atropine', 'calcium gluconate', 'captopril', 'carvedilol', 'cefazolin',
    'cefepime', 'ceftriaxone', 'clonazepam', 'clopidogrel', 'dextrose', 'diazepam',
    'digoxin(?!.*fab)', 'diltiazem', 'diphenhydramine', 'enoxaparin', 'epoetin', 'fentanyl',
    'fentanyl citrate', 'fluconazole', 'fondaparinux', 'furosemide', 'glucagon', 'haloperidol',
    'heparin', 'hydralazine', 'hydrochlorothiazide', 'hydromorphone', 'insulin', 'ipratropium',
    'labetalol', 'levetiracetam', 'levofloxacin', 'levothyroxine', 'lisinopril',
    'magensium sulfate', 'meropenem', 'metoclopramide', 'metoprolol', 'metronidazole', 'midazolam',
    'nafcillin', 'neostigmine', 'nitroglycerin', 'nitroprusside', 'norepinephrine', 'ondansetron',
    'oxacillin', 'oxycodone', 'pantoprazole', 'penicillin', 'phenylephrine', 'phenytoin',
    'phytonadione', 'piperacillin', 'potassium_y', 'prednisone', 'propofol', 'ranitidine',
    'statin', 'tacrolimus', 'trazodone', 'vasopressin', 'warfarin', 'zolpidem',
]
